const playerOneRunningRight = ">"
const playerOneRunningLeft = "<"
const playerOneIdle = ":"
const playerTwoRunningRight = "("
const playerTwoRunningLeft = ")"
const playerTwoIdle = "*"
const tagged = "!"

setLegend(
  [ playerOneRunningRight, bitmap`
................
.....0000000....
....0.......0...
...0..3..3..0...
...0..3..3..0...
...0........0...
...0........0...
....0......0....
.....0....0.....
.....0....0.....
.....0....0.....
....0......0....
...0...00...0...
..0...0..0..0...
...000....0.0...
...........0....` ],
  [ playerOneRunningLeft, bitmap`
................
....0000000.....
...0.......0....
...0..3..3..0...
...0..3..3..0...
...0........0...
...0........0...
....0......0....
.....0....0.....
.....0....0.....
.....0....0.....
....0......0....
...0...00...0...
...0..0..0...0..
...0.0....000...
....0...........` ],
  [ playerOneIdle, bitmap`
................
.....0000000....
....0.......0...
...0..3...3..0..
...0..3...3..0..
...0.........0..
...0.........0..
....0.......0...
.....0.....0....
.....0.....0....
.....0.....0....
.....0.....0....
.....0.....0....
.....0..0..0....
.....0.0.0.0....
.....00..00.....` ],
  [ playerTwoRunningRight, bitmap`
................
.....0000000....
....0.......0...
...0..5..5..0...
...0..5..5..0...
...0........0...
...0........0...
....0......0....
.....0....0.....
.....0....0.....
.....0....0.....
....0......0....
...0...00...0...
..0...0..0..0...
...000....0.0...
...........0....` ],
  [ playerTwoRunningLeft, bitmap`
................
....0000000.....
...0.......0....
...0..5..5..0...
...0..5..5..0...
...0........0...
...0........0...
....0......0....
.....0....0.....
.....0....0.....
.....0....0.....
....0......0....
...0...00...0...
...0..0..0...0..
...0.0....000...
....0...........` ],
  [ playerTwoIdle, bitmap`
................
.....0000000....
....0.......0...
...0..5...5..0..
...0..5...5..0..
...0.........0..
...0.........0..
....0.......0...
.....0.....0....
.....0.....0....
.....0.....0....
.....0.....0....
.....0.....0....
.....0..0..0....
.....0.0.0.0....
.....00..00.....` ],
  [ tagged, bitmap`
................
................
................
................
................
................
................
................
................
...0........0...
...00......00...
....00....00....
.....00..00.....
......0000......
.......00.......
................` ],
)

setSolids([])

let level = 0
const levels = [
  map`
..............
..............
..............
..............
..............
...!..........
...:......*...
..............
..............
..............
..............`
]

function delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

let it = 1
let playerOne = playerOneIdle
let playerTwo = playerTwoIdle

setMap(levels[level])

onInput("w", () => {
  if (it == 1) {
    getFirst(tagged).y -= 2
  }
  getFirst(playerOne).y -= 2
})

onInput("a", () => {
  let x = getFirst(playerOne).x
  let y = getFirst(playerOne).y
  playerOne = playerOneRunningLeft
  clearTile(x, y)
  addSprite(x, y, '<')
  
  if (it == 1) {
    getFirst(tagged).x -= 1
  }
  getFirst(playerOne).x -= 1
})

onInput("d", () => {
  let x = getFirst(playerOne).x
  let y = getFirst(playerOne).y
  playerOne = playerOneRunningRight
  clearTile(x, y)
  addSprite(x, y, '>')
  
  if (it == 1) {
    getFirst(tagged).x += 1
  }
  getFirst(playerOne).x += 1
})

onInput("i", () => {
  if (it == 2) {
    getFirst(tagged).y -= 1
  }
  getFirst(playerTwo).y -= 1
})

onInput("j", () => {
  let x = getFirst(playerTwo).x
  let y = getFirst(playerTwo).y
  playerTwo = playerTwoRunningLeft
  clearTile(x, y)
  addSprite(x, y, ')')
  
  if (it == 2) {
    getFirst(tagged).x -= 1
  }
  getFirst(playerTwo).x -= 1
})

onInput("l", () => {
  let x = getFirst(playerTwo).x
  let y = getFirst(playerTwo).y
  playerTwo = playerTwoRunningRight
  clearTile(x, y)
  addSprite(x, y, '(')
  
  if (it == 2) {
    getFirst(tagged).x += 1
  }
  getFirst(playerTwo).x += 1
})

afterInput(async () => {
  await delay(400);
  let x = getFirst(playerOne).x
  let y = getFirst(playerOne).y
  playerOne = playerOneIdle
  clearTile(x, y)
  addSprite(x, y, ':')

  
  x = getFirst(playerTwo).x
  y = getFirst(playerTwo).y
  playerTwo = playerTwoIdle
  clearTile(x, y)
  addSprite(x, y, '*')
  
  const applyGravityWithDelay = (sprite) => {
    const fallDelay = 400;
    let isSolidBelow = false;

    const fallInterval = setInterval(() => {
      const tileBelow = getTile(sprite.x, sprite.y + 1);
      const hasSolidBelow = tileBelow.some(s => s.type === wall);

      if (!hasSolidBelow && !isSolidBelow) {
        sprite.y += 1;
      } else {
        isSolidBelow = true;
        setTimeout(() => {
          isSolidBelow = getTile(sprite.x, sprite.y + 1).some(s => s.type === wall);
          if (isSolidBelow) {
            sprite.y += 1;
          }
          if (isSolidBelow) {
            clearInterval(fallInterval);
          }
        }, fallDelay);
      }

      if (isSolidBelow) {
        clearInterval(fallInterval);
      }
    }, fallDelay);
  }
  
  applyGravityWithDelay(getFirst(playerOne));

  applyGravityWithDelay(getFirst(playerTwo));

  applyGravityWithDelay(getFirst(tagged));
})